---

- name: "Install fail2ban"
  ansible.builtin.apt:
    name: fail2ban
    state: present
    update_cache: true
    cache_valid_time: 86400
  when: ansible_facts['os_family'] == "Debian"
  notify:
    - Start fail2ban

- name: "Install fail2ban RedHat"
  ansible.builtin.yum:
    name: fail2ban
    state: present
  when: ansible_facts['os_family'] == "RedHat"
  notify:
    - Start fail2ban

- name: "Deploy configuration for fail2ban"
  ansible.builtin.template:
    dest: "/etc/fail2ban/jail.d/{{ item.key }}.conf"
    src: config.j2
    mode: "0644"
    owner: root
    group: root
  loop: "{{ fail2ban_jaild_configs | dict2items }}"
  when: fail2ban_jaild_configs is defined and fail2ban_jaild_configs | length > 0
  notify:
    - Restart fail2ban
